mappings:
  GridFieldAddSortableMenuItem: Symbiote\SortableMenu\GridFieldAddSortableMenuItem
  SortableMenuManageExtension: Symbiote\SortableMenu\SortableMenuManageExtension
  SortableMenuException: Symbiote\SortableMenu\SortableMenuException
  SortableMenu: Symbiote\SortableMenu\SortableMenuExtension
  SortableMenuDBTest: Symbiote\SortableMenu\Tests\SortableMenuDBTest
  SortableMenuSiteConfigTest: Symbiote\SortableMenu\Tests\SortableMenuSiteConfigTest
  SortableMenuRenderingTest: Symbiote\SortableMenu\Tests\SortableMenuRenderingTest
  SortableMenuMultisitesTest: Symbiote\SortableMenu\Tests\SortableMenuMultisitesTest
